version: '3.8'

services:
  cassandra:
    image: cassandra:5.0.4
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=jaeger
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      # set Cassandra to /var/lib/cassandra
      - ./cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 15s
      timeout: 10s
      retries: 10

  jaeger-schema:
    image: jaegertracing/jaeger-cassandra-schema:latest
    container_name: jaeger-schema
    environment:
      - CQLSH_HOST=cassandra
      - KEYSPACE=jaeger_v1_dc1
      - DATACENTER=dc1
    depends_on:
      cassandra:
        condition: service_healthy

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # jaeger-collector (HTTP)
      - "14250:14250" # jaeger-collector (gRPC)
      - "6831:6831/udp" # jaeger-agent (UDP)
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    environment:
      - SPAN_STORAGE_TYPE=cassandra
      - CASSANDRA_SERVERS=cassandra
      - CASSANDRA_KEYSPACE=jaeger_v1_dc1
    depends_on:
      - jaeger-schema
    command:
      - "--cassandra.keyspace=jaeger_v1_dc1"
      - "--cassandra.servers=cassandra"