version: '3.8'

services:
  cassandra:
    image: cassandra:5.0.4
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=jaeger
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_COMMITLOG_TOTAL_SPACE_IN_MB=512
    volumes:
      # set Cassandra to /var/lib/cassandra
      - ./cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 15s
      timeout: 10s
      retries: 10

  jaeger:
    image: jaegertracing/all-in-one:1.72.0
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # jaeger-collector (HTTP)
      - "14250:14250" # jaeger-collector (gRPC)
      - "6831:6831/udp" # jaeger-agent (UDP)
      # - "4317:4317" # OTLP gRPC for jaeger
      # - "4318:4318" # OTLP HTTP for jaeger
    environment:
      - SPAN_STORAGE_TYPE=cassandra
      - CASSANDRA_SERVERS=cassandra
      - CASSANDRA_KEYSPACE=jaeger_v1_dc1
    depends_on:
      cassandra:
        condition: service_healthy
    command:
      - "--cassandra.keyspace=jaeger_v1_dc1"
      - "--cassandra.servers=cassandra"
      - "--collector.otlp.enabled=true"

  otel-collector:
    # use contrib version
    image: otel/opentelemetry-collector-contrib:0.131.0
    container_name: otel-collector
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"  # OTLP gRPC for service
      - "4318:4318"  # OTLP HTTP for service
      - "8889:8889"  # Prometheus metrics endpoint for Prometheus
    depends_on:
      - jaeger
      # - loki

  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    ports: ["9090:9090"]
    volumes: ["./prometheus.yml:/etc/prometheus/prometheus.yml"]
    command: ['--config.file=/etc/prometheus/prometheus.yml']
    depends_on:
      - otel-collector # Prometheus need Collector